### ISSUE TITLE
Not loading assembly Ghpr.SerilogToSeqLogger.dll

### ISSUE THREAD

**Issue by andre2test** [GHPReporter/Ghpr.SpecFlow.Examples#3]
Hi,

Just loaded the new version of GHPReporter which supports SpecFlow 2.4. 
I searched under $PROJECT\bin\Debug directory and did not locate Ghpr.SerilogToSeqLogger.dll
I have to disable the GHP Reporter again from my project.  

Attached packages.config file.   Below is the error I got
**packages.config**
 <?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Common.Logging" version="3.4.1" targetFramework="net461" />
  <package id="Common.Logging.Core" version="3.4.1" targetFramework="net461" />
  <package id="Common.Logging.NLog20" version="3.3.1" targetFramework="net461" />
  <package id="Ghpr.Core" version="0.9.3" targetFramework="net461" />
  <package id="Ghpr.LocalFileSystem" version="0.9.2" targetFramework="net461" />
  <package id="Ghpr.NUnit.SpecFlowPlugin" version="0.9.3" targetFramework="net461" />
  <package id="Ghpr.SpecFlow.Common" version="0.9.3" targetFramework="net461" />
  <package id="Microsoft.CSharp" version="4.5.0" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net461" />
  <package id="NLog" version="4.5.8" targetFramework="net461" />
  <package id="NUnit" version="3.10.1" targetFramework="net461" />
  <package id="NUnit.Engine" version="3.9.0" targetFramework="net461" />
  <package id="NUnit3TestAdapter" version="3.10.0" targetFramework="net461" />
  <package id="SpecFlow" version="2.4.0" targetFramework="net461" />
  <package id="SpecFlow.CustomPlugin" version="2.4.0" targetFramework="net461" />
  <package id="System.ValueTuple" version="4.5.0" targetFramework="net461" />
</packages>

------ Run test started ------
NUnit Adapter 3.10.0.21: Test execution started
Running selected tests in P:\P4WK\QA\Source\Compliance\QA\BDD_SDMP\bin\Debug\BDD_SDMP.dll
NUnit3TestExecutor converted 257 of 257 NUnit test cases
TearDown failed for test fixture BDD_SDMP.Features.SELF_TRADE.CST001_SelfTradeWithin60SecondsFeature
System.IO.FileNotFoundException : Could not load file or assembly 'file:///P:\P4WK\QA\Source\Compliance\QA\BDD_SDMP\bin\Debug\Ghpr.SerilogToSeqLogger.dll' or one of its dependencies. The system cannot find the file specified.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Ghpr.Core.Factories.ReporterFactory.CreateInstanceFromFile[T](String fileName, T defaultImplementation)
   at Ghpr.Core.Factories.ReporterFactory.InitializeReporter(ReporterSettings settings, ITestDataProvider testDataProvider)
   at Ghpr.Core.ReporterManager.Initialize(TestingFramework framework, ITestDataProvider testDataProvider)
   at GhprNUnit.SpecFlowPlugin.GhprNUnitSpecFlowPlugin.Initialize(RuntimePluginEvents runtimePluginEvents, RuntimePluginParameters runtimePluginParameters)
   at TechTalk.SpecFlow.Infrastructure.ContainerBuilder.LoadPlugin(PluginDescriptor pluginDescriptor, IRuntimePluginLoader pluginLoader, RuntimePluginEvents runtimePluginEvents)
   at TechTalk.SpecFlow.Infrastructure.ContainerBuilder.LoadPlugins(IRuntimeConfigurationProvider configurationProvider, ObjectContainer container, RuntimePluginEvents runtimePluginEvents, SpecFlowConfiguration specFlowConfiguration)
   at TechTalk.SpecFlow.Infrastructure.ContainerBuilder.CreateGlobalContainer(IRuntimeConfigurationProvider configurationProvider)
   at TechTalk.SpecFlow.TestRunnerManager.CreateTestRunnerManager(Assembly testAssembly, IContainerBuilder containerBuilder)
   at TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerManager(Assembly testAssembly, IContainerBuilder containerBuilder)
   at TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(Assembly testAssembly, Nullable`1 managedThreadId)

**Comment by elv1s42** [comment]
Hi @andre2test ,

Thank you for this issue.
Unfortunately I can't find the file `packages.config` attached.

Can you please check you are using the latest vesion of all Ghpr packages?

Also can you please send me your content of `Ghpr.SpecFlow.Settings.json` file?

Please check that `"loggerFile": ""` in that file.

Thank you

**Comment by elv1s42** [comment]
I've removed the loggerFileName forom default `Ghpr.SpecFlow.Settings.json`, the change released under v0.9.3.1 for Ghpr.SpecFlow.Common.
But you can simply modify `Ghpr.SpecFlow.Settings.json` file to have `"loggerFile": ""`.

**Comment by andre2test** [comment]
Ok, I will try that.  I copied and pasted the packages.config file.

Best Regards

**Comment by andre2test** [comment]
Thank you, that worked, getting reports again!  FYI, clean out previously generated GHPReport files.

**Comment by elv1s42** [comment]
Great, thank you for the update!
